config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework import routers

from sahem.events import views

router = routers.DefaultRouter()
router.register(r'events', views.EventViewSet)
router.register(r'users', views.UserViewSet)
router.register(r'categories', views.CategoryViewSet)
router.register(r'comments', views.CommentViewSet)
urlpatterns = [
                  url(r'^$', TemplateView.as_view(template_name='base.html'), name="home"),
                  url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
                  url(r'^privacy\-policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'),
                      name="privacy_policy"),

                  # Django Admin, use {% url 'admin:index' %}
                  url(settings.ADMIN_URL, include(admin.site.urls)),

                  # User management
                  url(r'^users/', include("sahem.users.urls", namespace="users")),
                  url(r'^accounts/', include('allauth.urls')),

                  # Your stuff: custom urls includes go here
                  url(r'^events/', include('sahem.events.urls', namespace='events')),

                  # Join event api
                  url(r'^api/events/join/event/(?P<event_id>\d+)/staff/(?P<staff_id>\d+)/$', views.join_event,
                      name='join_event_as_staff'),
                  url(r'^api/events/join/event/(?P<event_id>\d+)/participant/(?P<participant_id>\d+)/$',
                      views.join_event,
                      name='join_event_as_participant'),

                  # Leave event api
                  url(r'^api/events/leave/event/(?P<event_id>\d+)/staff/(?P<staff_id>\d+)/$', views.leave_event,
                      name='leave_event_as_staff'),
                  url(r'^api/events/leave/event/(?P<event_id>\d+)/participant/(?P<participant_id>\d+)/$',
                      views.leave_event,
                      name='leave_event_as_participant'),

                  # Comments api
                  url(r'^api/comments/add/$', views.add_comment, name='add_comment'),
                  # Api Endpoint
                  url(r'^api/events/(?P<id>\d+)/(?P<slug>\w+)/$', views.event_list, name='event_by_id_slug'),
                  url(r'^api/events/category/(?P<category_slug>\w+)/$', views.event_list, name='event_by_category'),
                  url(r'^api/', include(router.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

sahem/events/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [

    # Category and Event list
    url(r'^$', views.list, name='list'),
    url(r'^category/(?P<category_slug>[-\w]+)/$', views.list, name='event_list_by_category'),

    # Event detail
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.detail, name='detail'),

    # Event create update and delete
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
    url(r'^update/(?P<pk>\d+)/$', views.EventUpdateView.as_view(), name='update'),

]

sahem/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.detail,
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

sahem/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):
    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    image = models.ImageField(upload_to='profile_images/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

sahem/events/forms.py
from django import forms

from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'category', 'description', 'start', 'end', 'position', ]

sahem/events/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.datetime_safe import datetime
from django.utils.text import slugify
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import UpdateView
from rest_framework import viewsets
from rest_framework.parsers import JSONParser
from rest_framework.renderers import JSONRenderer

import json

from sahem.events.serializers import EventSerializer, UserSerializer, CategorySerializer, CommentSerializer
from sahem.users.models import User
from .forms import EventForm
from .models import Event, Category, Comment


class JSONResponse(HttpResponse):
    """
    An HttpResponse that renders its content into JSON.
    """

    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


def list(request, category_slug=None):
    category = None
    categories = Category.objects.all()

    events = Event.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        events = events.filter(category=category)

    return render(request, 'events/list.html', locals())


def detail(request, id, slug):
    event = get_object_or_404(Event, pk=id, slug=slug)

    if event.end.day < datetime.now().day:
        event.available = False

    return render(request, 'events/detail.html', locals())


@login_required
def create(request):
    print request.POST

    if request.method == 'POST':
        form = EventForm(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner = request.user
            instance.slug = slugify(instance.name)

            instance.save()

            context = {
                'message': 'Event created',
                'flag': 'success',
            }

            # return render(request, 'events/create.html', context)
            return redirect('/#/events')

        else:
            context = {
                'message': 'Form is invalid',
                'flag': 'error',
                'form': form,
            }
            return render(request, 'events/create.html', context)

    else:
        form = EventForm()

    context = {
        'form': form,
    }

    return render(request, 'events/create.html', context)


@login_required
def delete(request, id):
    event = get_object_or_404(Event, pk=id)

    # check if the sender is the acctual owner of the event
    if request.user == event.owner:
        event.delete()
    else:
        raise Http404
    return redirect('events:list')


class EventUpdateView(LoginRequiredMixin, UpdateView):
    form_class = EventForm
    template_name = 'events/update.html'
    # we already imported User in the view code above, remember?
    model = Event

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("events:list")


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


@csrf_exempt
def event_list(request, id=None, slug=None, category_slug=None):
    if request.method == 'GET':

        if category_slug:
            events = Event.objects.filter(category__slug=category_slug)
        elif id and slug:
            events = Event.objects.filter(id=id, slug=slug)
        else:
            events = Event.objects.all()
        serializer = EventSerializer(events, many=True)
        return JSONResponse(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = EventSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data, status=201)

        else:
            return JSONResponse(serializer.errors, status=400)


@csrf_exempt
def event_detail(request, pk):
    """
    Retrieve, update or delete a code event.
    """
    try:
        event = Event.objects.get(pk=pk)
    except Event.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = EventSerializer(event)
        return JSONResponse(serializer.data)

    elif request.method == 'PUT':

        #  slugify the name before saving
        request.POST['slug'] = slugify(request.POST['name'])

        data = JSONParser().parse(request)
        serializer = EventSerializer(event, data=data)
        if serializer.is_valid():
            serializer.save()
            return JSONResponse(serializer.data)
        return JSONResponse(serializer.errors, status=400)

    elif request.method == 'DELETE':
        event.delete()
        return HttpResponse(status=204)


@csrf_exempt
def join_event(request, event_id, staff_id=None, participant_id=None):
    staff_ids = []
    participant_ids = []

    # get the acctual event from the database
    try:
        event = Event.objects.get(pk=event_id)
    except Event.DoesNotExist:
        return HttpResponse(status=404)

    # get all staff ids
    for i in event.staff.all():
        staff_ids.append(i.id)

    # get all participants ids
    for i in event.participant.all():
        participant_ids.append(i.id)

    print '-------------------------------------'
    print "staff ids : " + str(staff_ids)
    print 'participant ids' + str(participant_ids)

    # if it's a staff request
    if staff_id:
        try:
            staff = User.objects.get(pk=staff_id)
            # convert the staff id to an integer
            staff_id = int(staff_id)
            if staff_id not in staff_ids and staff_id not in participant_ids and staff != event.owner:
                event.staff.add(staff)

        except User.DoesNotExist:
            return HttpResponse(status=404)

    # if it's a participant request
    elif participant_id:
        try:
            participant = User.objects.get(pk=participant_id)
            # convert the participant id to an integer
            participant_id = int(participant_id)

            if participant_id not in participant_ids and participant_id not in staff_ids and participant != event.owner:
                event.participant.add(participant)


        except User.DoesNotExist:
            return HttpResponse(status=404)

    serializer = EventSerializer(event)

    return JSONResponse(serializer.data)


@csrf_exempt
def leave_event(request, event_id, staff_id=None, participant_id=None):
    # get the event from the data base
    try:
        event = Event.objects.get(id=event_id)
    except Event.DoesNotExist:
        return HttpResponse(status=404)

    # if the user was a staff a this event
    if staff_id:
        event.staff.remove(staff_id)
    # else if he is a participant at this event
    elif participant_id:
        event.participant.remove(participant_id)

    # get back the responce a serialized event data
    serializer = EventSerializer(event)
    return JSONResponse(serializer.data)


@csrf_exempt
def add_comment(request):

    data =  json.loads(request.body)

    print data['user_id']
    print data['comment']

    try:
        event = Event.objects.get(id=data['event_id'])
    except Event.DoesNotExist:
        return HttpResponse(status=404)

    try:
        user = User.objects.get(id=data['user_id'])
    except User.DoesNotExist:
        return HttpResponse(status=404)

    comment_obj = Comment.objects.create(user=user, content=data['comment'])
    comment_obj.save()

    event.comments.add(comment_obj)
    event.save()


    serializer = EventSerializer(event)

    return JSONResponse(serializer.data)

sahem/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.utils.datetime_safe import date, datetime
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.db.models import Q

from sahem.events.models import Event, Comment
from .models import User


# class UserDetailView(LoginRequiredMixin, DetailView):
#     model = User
#     # These next two lines tell the view to index lookups by username
#     slug_field = "username"
#     slug_url_kwarg = "username"


def detail(request, username):
    # Get the user
    user = User.objects.get(username=username)

    owner_events = []
    current_events = []
    upcoming_events = []
    finished_events = []
    comments = []

    # Get all owner created events
    try:
        owner_events = Event.objects.filter(owner=user)
    except:
        pass

    # Get all the current events
    try:
        current_events = Event.objects.filter(Q(staff__username=username) | Q(participant__username=username),
                                              Q(start__lte=date.today()) & Q(end__gt=date.today()))
    except:
        pass

    # Get all the upcomming events
    try:
        upcoming_events = Event.objects.filter(Q(staff__username=username) | Q(participant__username=username),
                                               Q(start__gt=date.today()))
    except:
        pass

    # Get all the finished events
    try:
        finished_events = Event.objects.filter(Q(staff__username=username) | Q(participant__username=username),
                                               Q(end__lt=date.today()))
    except:
        pass
    events_count = len(current_events) + len(upcoming_events)
    current_count = len(current_events)
    upcoming_count = len(upcoming_events)
    finished_count = len(finished_events)

    # Get all comments realted to the user fillter by latest adedd
    try:
        comments = Comment.objects.filter(user=user).order_by('created')
    except:
        pass

    print 'current events :' + str(current_events)
    print 'upcomming events :' + str(upcoming_events)
    print 'comments :' + str(comments)
    context = {
        'user': user,
        'owner_events': owner_events,
        'current_events': current_events,
        'upcoming_events': upcoming_events,
        'comments': comments,
        'events_count': events_count,
        'current_count': current_count,
        'upcoming_count': upcoming_count,
        'finished_count': finished_count

    }
    return render(request, 'users/user_detail.html', context)


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

sahem/templates/events/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load material_form %}

{% block title %}Create Event{% endblock %}
{% block content %}

    {# Load the jquery to display the map #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <div class="container" id="form-control">

        <div id="create-form" class="container">

            {% if message %}
{#                <div class="alert alert-{{ flag }}">#}
{#                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>#}
{#                    <strong>{{ message }}</strong>#}
{#                </div>#}
            {% endif %}



            <div class="card">
                <div class="card-content">
                    {% if form %}

                        <form action="" method="post">
                            {% csrf_token %}
                            {% form form=form %}{% endform %}
                            {{ form.media }}
                            <button class="btn btn-default" type="submit">Create</button>
                        </form>


                    {% endif %}
                </div>
            </div>

        </div>

    </div>

{% endblock %}

sahem/templates/events/detail.html
{% extends 'base.html' %}
{% block title %}{{ event.name }}{% endblock %}
{% block content %}



    <script src="http://maps.googleapis.com/maps/api/js"></script>
    <script>
        function initialize() {
            var mapProp = {
                center: new google.maps.LatLng({{ event.position.latitude }}, {{ event.position.longitude }}),
                zoom: 15,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);


            var myLatLng = {lat: {{ event.position.latitude }}, lng: {{ event.position.longitude }}};

            var marker = new google.maps.Marker({
                position: myLatLng,
                map: map,
                title: 'hello world'
            })

        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    <!-- ----------------------------------------------- -->
    <div class="card event-page-elem">
        {% if event.available %}
            <div class="green">This event is available</div>
        {% else %}
            <div class="red">This event is not available</div>
        {% endif %}
        <div class="row">
            <div class="cards-content">
                <div class="card-title">
                    <div class="row">
                        <div class="col s1">
                            <img src="{{ event.category.image.url }}" alt="{{ event.category.name }}"
                                 class="responsive-img circle">
                        </div>
                        <div class="col s11">
                            <p><strong>{{ event.name }}</strong><br>
                                {{ event.category.name }} event, starts on {{ event.start }}</p>

                        </div>
                    </div>
                    <div class="divider"></div>
                </div>
                <div class="col s8">

                    <h3>Event details</h3>
                    <p class="flow-text">{{ event.description }}</p>

                    <h3>Who's Going</h3>
                    <p>Manager : {{ event.owner }}</p>
                    <p>Staffs : {{ event.get_staff_count }}</p>
                    <ul class="list-unstyled">
                        {% for staff in event.staff.all %}
                            <li>{{ staff }}</li>
                        {% endfor %}
                    </ul>
                    <p>Participant : {{ event.get_participant_count }}</p>
                    <p>
                        {% for participant in event.participant.all %}
                            {{ participant }},
                        {% endfor %}
                    </p>
                    <h3>What we need ?</h3>
                    <p>list display here</p>

                </div>

                <!--Map -->
                <div class="col s4">
                    <div class="card">
                        <div class="card-image">
                            <div id="googleMap"></div>
                        </div>
                        <div class="card-content">
                            <h4>When ?</h4>
                            <p><b>Start: </b>{{ event.start }} <br><b>Ends: </b>{{ event.end }}</p>

                            <h4>Where ?</h4>
                            <!--todo: event address -->
                            <p>EVENT ADRESS Here</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% if request.user == event.owner %}
            <div class="card-action">
                <a class="waves-effect waves-light btn"
                   href="{% url 'events:update' event.id %}">Update</a>
                <a class="waves-effect waves-light btn modal-trigger"
                   href="#delete-modal">Delete</a>
            </div>
        {% endif %}

    </div>
    <div class="card event-page-elem">

        <div class="card-action">
            <p>Share this !</p>

            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_native_toolbox"></div>

        </div>
    </div>
    <!-- ----------------------------------------------- -->

    <!--

    -->



    <!-- Modal Trigger -->


    <!-- Modal Structure -->
    <div id="delete-modal" class="modal">
        <div class="modal-content">
            <h4>Modal Header</h4>
            <p>A bunch of text</p>
        </div>
        <div class="modal-footer">
            <a href="" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancel</a>
            <a class=" modal-action modal-close waves-effect waves-green btn-flat"
               onclick="$('#delete-modal').closeModal();" href="{% url 'events:delete' event.id %}">Agree</a>
        </div>
    </div>

    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53579a8052432245"></script>
{% endblock %}
{% block footer %}{% endblock %}

<!--todo: Ida matasa79hach gla3ha -->
<div>
    {#{% if event.owner == request.user %}
                    <!--
                        <div class="card-action">
                            <a href="{% url 'events:update' event.id %}" class="btn btn-default">Update</a>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-default" data-toggle="modal"
                                    data-target="#remove-event-modal">
                                Remove
                            </button>
                        </div>
                        -->
                    {% endif %}#}
</div>

sahem/templates/events/list.html
{% extends 'base.html' %}
{% block title %}Events{% endblock %}
{% block content %}


    <div class="container">

        <div class="row">
            <div class="col m2">

                <div class="collection ">
                    <a href="{% url 'events:list' %}"
                       class="collection-item{% if not category %} active deep-purple accent-2 white-text{% else %} black-text {% endif %}">All</a>
                    {% for cat in categories %}
                        <a href="{{ cat.get_absolute_url }}"
                           class="collection-item{% if cat == category %} active deep-purple accent-2 white-text {% else %} black-text {% endif %}">{{ cat.name }}</a>
                    {% endfor %}
                </div>

            </div>

            <div class="col m10">
                <ul class="collapsible popout" data-collapsible="accordion">
                    {% for event in events %}
                        <li>
                            <div class="collapsible-header">
                                <img id="event-list-img" src="{{ event.category.image.url }}" class="circle"
                                     height="48">
                                <span><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></span>
                            </div>
                            <div class="collapsible-body"><p>{{ event.description }}</p></div>
                        </li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>


    <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
        <a class="btn-floating btn-large dark-orange accent-2" href="{% url 'events:create' %}">
            <i class="material-icons">add</i>
        </a>
    </div>

{% endblock %}

sahem/templates/events/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}update {{ event.name }}{% endblock %}
{% block content %}


    {# Load the jquery to display the map #}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

    <div id="update-form" class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            {{ form.media }}
            <button id="update-event-btn" type="submit" class="btn btn-default">Update</button>
        </form>
    </div>

{% endblock %}